### PR TITLE
add xls file and changes in scrap_career.py

### PR DESCRIPTION
**Pull request by Ragh2018**
i added this after cloning from master branch but their is an issue.
screenshot from 2016-09-11 19-41-55

### CODE REVIEW

**Comment by gupta-shantanu** [comment]
@Ragh2018 The "No File or directory" error occurs because windows type address were used, They have been fixed using _os paths_ . No need to change the directory structure.
Your pull request conflicts with the master. Please update your fork and make your changes in updated branch, so that diff is clear. I am unable to see the changes you made.

**Comment by Ragh2018** [comment]
yes shantanu i have not changes in file but there is problem while running it.Can you tell me how can i fix it for linux.

**Comment by gupta-shantanu** [comment]
If you haven't made any changes in the file, you should update your fork by pulling rohitmanglik:master
, let me know if it still doesn't work.

**Comment by Ragh2018** [comment]
okk

**Comment by Ragh2018** [comment]
issue is fixed after pull.
shantanu i need a little bit of guidance according to this project.
What we are going to do with much amount of dataset.
On which technology we are going to work.

**Comment by rohitmanglik** [comment]
This pull request doesn't address the issue in hand. Closing the request.

**Pull request closed without merging**
